SistemaLoja/Controllers/OrdensController.cs
using SistemaLoja.Models;
using SistemaLoja.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaLoja.Controllers
{
    public class OrdensController : Controller
    {
        private SistemaLojaContext db = new SistemaLojaContext();
        // GET: Ordens
        public ActionResult NovaOrdem()
        {
            var ordemView = new OrdemView();
            ordemView.Customizar = new Customizar();
            ordemView.Produtos = new List<ProdutoOrdem>();
            Session["ordemView"] = ordemView;

            var list = db.Customizars.ToList();
            //list.Add(new TipoDocumento { TipoDocumentoId = 0, Descricao = "[Selecione o tipo de Documento]" });
            list = list.OrderBy(c => c.NomeCompleto).ToList();
            ViewBag.CustomizarId = new SelectList(list, "CustomizarId", "NomeCompleto");
            return View(ordemView);

        }

        [HttpPost]
        public ActionResult NovaOrdem(OrdemView ordemView)
        {
            ordemView = Session["ordemView"] as OrdemView;
            var customizarId = int.Parse(Request["CustomizarId"]);
            var list = db.Customizars.ToList();

            if (customizarId == 0)
            {
                list = db.Customizars.ToList();
                list.Add(new Customizar { CustomizarId = 0, Nome = "[Selecione um Cliente]" });
                list = list.OrderBy(c => c.NomeCompleto).ToList();
                ViewBag.CustomizarId = new SelectList(list, "CustomizarId", "NomeCompleto");
                ViewBag.Error = "Selecione um cliente";



                return View(ordemView);

            }

            var cliente = db.Customizars.Find(customizarId);
            if (cliente == null)
            {

                list = db.Customizars.ToList();
                list.Add(new Customizar { CustomizarId = 0, Nome = "[Selecione um Cliente]" });
                list = list.OrderBy(c => c.NomeCompleto).ToList();
                ViewBag.CustomizarId = new SelectList(list, "CustomizarId", "NomeCompleto");
                ViewBag.Error = "Selecione um cliente";

                return View(ordemView);
            }

            if (ordemView.Produtos.Count == 0)
            {
                list = db.Customizars.ToList();
                list.Add(new Customizar { CustomizarId = 0, Nome = "[Selecione um Cliente]" });
                list = list.OrderBy(c => c.NomeCompleto).ToList();
                ViewBag.CustomizarId = new SelectList(list, "CustomizarId", "NomeCompleto");
                ViewBag.Error = "Selecione um Produto";
                return View(ordemView);
            }

            int ordemId = 0;
            using (var transaction = db.Database.BeginTransaction())
            {
                try
                {
                    var ordem = new Ordem
                    {
                        CustomizarId = customizarId,
                        OrdemData = DateTime.Now,
                        OrdemStatus = OrdemStatus.Criada
                    };

                    db.Ordem.Add(ordem);
                    db.SaveChanges();

                    ordemId = db.Ordem.ToList().Select(o => o.OrdemId).Max();
                    foreach (var item in ordemView.Produtos)
                    {
                        var ordemDetalhes = new OrdemDetalhe
                        {
                            ProdutoId = item.ProdutoId,
                            Descricao = item.Descricao,
                            Quantidade = item.Quantidade,
                            Preco = item.Preco,
                            OrdemId = ordemId
                        };
                        db.OrdemDetalhe.Add(ordemDetalhes);
                        db.SaveChanges();
                    }
                    transaction.Commit();
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                    ViewBag.Error = "Error" + ex.Message;
                    return View(ordemView);
                    
               }
            
        }
            ViewBag.Mensagem = string.Format("Ordem: {0}, foi salva com sucesso", ordemId);


            list = db.Customizars.ToList();
            list.Add(new Customizar { CustomizarId = 0, Nome = "[Selecione um Cliente]" });
            list = list.OrderBy(c => c.NomeCompleto).ToList();
            ViewBag.CustomizarId = new SelectList(list, "CustomizarId", "NomeCompleto");
            ViewBag.Error = "Selecione um cliente";

            ordemView = new OrdemView();
            ordemView.Customizar = new Customizar();
            ordemView.Produtos = new List<ProdutoOrdem>();
            Session["ordemView"] = ordemView;

            return View(ordemView);

        }
        
        public ActionResult AddProduto()
        {
            var list = db.Produtoes.ToList();
            list.Add(new ProdutoOrdem { ProdutoId = 0, Descricao = "[Selecione o tipo de Documento]" });
            list = list.OrderBy(c => c.Descricao).ToList();
            ViewBag.ProdutoId = new SelectList(list, "ProdutoId", "Descricao");
            return View();

        }

        [HttpPost]
        public ActionResult AddProduto(ProdutoOrdem produtoOrdem)
        {

            var ordemView = Session["ordemView"] as OrdemView;

            var list = db.Produtoes.ToList();
            var produtoId = int.Parse(Request["ProdutoId"]);

            if (produtoId == 0)
            {
                
                list.Add(new ProdutoOrdem { ProdutoId = 0, Descricao = "[Selecione o tipo de Documento]" });
                list = list.OrderBy(c => c.Descricao).ToList();
                ViewBag.ProdutoId = new SelectList(list, "ProdutoId", "Descricao");
                ViewBag.Error = "o";

              

                return View(produtoOrdem);

            }

            var produto = db.Produtoes.Find(produtoId);
            if(produto == null)
            {

                list.Add(new ProdutoOrdem { ProdutoId = 0, Descricao = "[Selecione o tipo de Documento]" });
                list = list.OrderBy(c => c.Descricao).ToList();
                ViewBag.ProdutoId = new SelectList(list, "ProdutoId", "Descricao");
                ViewBag.Error = "Não existe o produto selecionado";

               

                return View(produtoOrdem);


            }

            produtoOrdem = ordemView.Produtos.Find(p => p.ProdutoId == produtoId);
            if(produtoOrdem == null )
            {           

            produtoOrdem = new ProdutoOrdem
            {
                Descricao = produto.Descricao,
                Preco = produto.Preco,
                ProdutoId = produto.ProdutoId,
                Quantidade = float.Parse(Request["Quantidade"]) 
            };

            ordemView.Produtos.Add(produtoOrdem);
            }else
            {
                produtoOrdem.Quantidade += float.Parse(Request["Quantidade"]);
            }
            var listC = db.Customizars.ToList();
            //listC.Add(new Customizar { CustomizarId = 0, Nome = "[Selecione o tipo de Documento]" });
            listC = listC.OrderBy(c => c.NomeCompleto).ToList();
            ViewBag.CustomizarId = new SelectList(listC, "CustomizarId", "NomeCompleto");
            return View("NovaOrdem", ordemView);


        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaLoja/Views/Ordens/AddProduto.cshtml
@model SistemaLoja.Models.ProdutoOrdem
@{
    ViewBag.Title = "AddProduto";
}

<h2>AddProduto</h2>
@using (Html.BeginForm())

  {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.ProdutoId, "ProdutoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProdutoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProdutoId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <input type="submit" value="Adicionar" id="Adicionar" class="btn btn-default" />
    </div>
}

SistemaLoja/Views/Ordens/NovaOrdem.cshtml
@model SistemaLoja.ViewModels.OrdemView

@{
    ViewBag.Title = "NovaOrdem";
}

<h2>Nova Ordem</h2>
<h5>@ViewBag.Error</h5>
<h5>@ViewBag.Mensagem</h5>
@using (Html.BeginForm("NovaOrdem", "Ordens", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Customizar.CustomizarId, "Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomizarId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Customizar.CustomizarId, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.ActionLink("Adicionar Produto", "AddProduto", new { }, new { @class="btn btn-primary" })
        
        <input type="submit" value="Criar" id="NovaOrdem"class="btn btn-default" />
    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Produto.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Produto.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Produto.Quantidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Produto.Valor)
        </th>
        <th></th>
    </tr>

    @for(int i =0; i < Model.Produtos.Count; i++)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => Model.Produtos[i].Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Produtos[i].Preco)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => Model.Produtos[i].Valor)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = Model.Produtos[i].ProdutoId }) |
                @Html.ActionLink("Excluir", "Delete", new { id = Model.Produtos[i].ProdutoId })
            </td>
        </tr>
    }

</table>